name: Build And Deploy

on:
  push:
    branches: [$default-branch]
  pull_request:
    branches: [$default-branch]

defaults:
  run:
    working-directory: infra

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: "lts/*"

      - name: Update npm
        run: npm install -g npm

      - name: Install cdk
        run: npm install -g aws-cdk

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Test
        run: npm run test

      - name: Synth
        run: cdk synth

  deploy_to_prod:
    name: Deploy To Prod
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: "lts/*"

      - name: Update npm
        run: npm install -g npm

      - name: Install cdk
        run: npm install -g aws-cdk
# TODO: capture synth output, deploy stuff
